trainer:
  accelerator: gpu
  devices: 1
  precision: 32
  gradient_clip_val: 10.0
  max_epochs: 10
  accumulate_grad_batches: 32

output: /home/ubuntu/sabdab_finetune/output
pretrained: /home/ubuntu/weights/boltz2_conf.ckpt
resume: null
disable_checkpoint: false
matmul_precision: null
save_top_k: -1

data:
  datasets:
    - _target_: boltz.data.module.training.DatasetConfig
      target_dir: /home/ubuntu/sabdab_finetune/targets
      msa_dir: /home/ubuntu/sabdab_finetune/msas
      prob: 1.0
      sampler:
        _target_: boltz.data.sample.cluster.ClusterSampler
      cropper:
        _target_: boltz.data.crop.boltz.BoltzCropper
        min_neighborhood: 0
        max_neighborhood: 32
      split: null

  filters:
    - _target_: boltz.data.filter.dynamic.size.SizeFilter
      min_chains: 2
      max_chains: 8

  tokenizer:
    _target_: boltz.data.tokenize.boltz.BoltzTokenizer
  featurizer:
    _target_: boltz.data.feature.featurizer.BoltzFeaturizer

  symmetries: null
  max_tokens: 384
  max_atoms: 3456
  max_seqs: 1024
  pad_to_max_tokens: true
  pad_to_max_atoms: true
  pad_to_max_seqs: true
  samples_per_epoch: 400
  batch_size: 1
  num_workers: 4
  random_seed: 17
  pin_memory: true
  overfit: null
  crop_validation: true
  return_train_symmetries: false
  return_val_symmetries: true
  train_binder_pocket_conditioned_prop: 0.0
  val_binder_pocket_conditioned_prop: 0.0
  binder_pocket_cutoff: 6.0
  binder_pocket_sampling_geometric_p: 0.0
  min_dist: 2.0
  max_dist: 22.0
  num_bins: 64
  atoms_per_window_queries: 32
  compute_constraint_features: false
  esm_profile:
    model_name: facebook/esm2_t33_650M_UR50D
    cache_dir: ./sabdab_esm_cache
    device: auto
    mix: 0.35

model:
  _target_: boltz.model.models.boltz2.Boltz2
  atom_s: 128
  atom_z: 16
  token_s: 384
  token_z: 128
  num_bins: 64
  atom_feature_dim: 388
  atoms_per_window_queries: 32
  atoms_per_window_keys: 128
  compile_pairformer: false
  ema: true
  ema_decay: 0.999

  embedder_args:
    atom_encoder_depth: 3
    atom_encoder_heads: 4

  msa_args:
    msa_s: 64
    msa_blocks: 4
    msa_dropout: 0.10
    z_dropout: 0.20
    pairwise_head_width: 32
    pairwise_num_heads: 4
    activation_checkpointing: true

  pairformer_args:
    num_blocks: 36
    num_heads: 16
    dropout: 0.2
    activation_checkpointing: true

  score_model_args:
    sigma_data: 16
    dim_fourier: 256
    atom_encoder_depth: 3
    atom_encoder_heads: 4
    token_transformer_depth: 16
    token_transformer_heads: 16
    atom_decoder_depth: 3
    atom_decoder_heads: 4
    conditioning_transition_layers: 2
    activation_checkpointing: true

  confidence_prediction: false
  confidence_model_args:
    num_dist_bins: 64
    max_dist: 22
    add_s_to_z_prod: true
    add_s_input_to_s: true
    use_s_diffusion: true
    add_z_input_to_z: true

    confidence_args:
      num_plddt_bins: 50
      num_pde_bins: 64
      num_pae_bins: 64

  training_args:
    recycling_steps: 3
    sampling_steps: 16
    diffusion_multiplicity: 8
    diffusion_samples: 2
    confidence_loss_weight: 1e-4
    diffusion_loss_weight: 4.0
    distogram_loss_weight: 3e-2
    weight_decay: 0.01
    adam_beta_1: 0.9
    adam_beta_2: 0.95
    adam_eps: 0.00000001
    lr_scheduler: cosine
    base_lr: 0.0
    max_lr: 0.0009
    lr_warmup_no_steps: 500
    lr_start_decay_after_n_steps: 20000
    lr_decay_every_n_steps: 20000
    lr_decay_factor: 0.9

  validation_args:
    recycling_steps: 1
    sampling_steps: 8
    diffusion_multiplicity: 4
    diffusion_samples: 1

  diffusion_process_args:
    sigma_min: 0.0004
    sigma_max: 160.0
    sigma_data: 16.0
    rho: 7
    P_mean: -1.2
    P_std: 1.5
    gamma_0: 0.8
    gamma_min: 1.0
    noise_scale: 1.0
    step_scale: 1.0
    coordinate_augmentation: true
    alignment_reverse_diff: true
    synchronize_sigmas: true

  diffusion_loss_args:
    add_smooth_lddt_loss: true
    nucleotide_loss_weight: 5.0
    ligand_loss_weight: 10.0
